export const stars = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
export const URL = 'https://pokeapi.co/api/v2/pokemon/'
export const URL_MOVES = 'https://pokeapi.co/api/v2/move/'
export const typeEmojiPokemon: any = {
    bug: '🐛',
    dark: '🌗',
    dragon: '🐉',
    electric: '⚡',
    fairy: '🧚',
    fighting: '🥊',
    fire: '🔥',
    flying: '🐦',
    ghost: '👻',
    grass: '🌱',
    ground: '⛰️',
    ice: '❄️',
    normal: '🐶',
    poison: '💉',
    psychic: '🧠',
    rock: '🪨',
    steel: '⚙️',
    water: '💧',
    other: '👾',
}
export const colorByTypePokemon: any = {
    bug: 'bg-lime-400 text-white text-xl lg:text-2xl',
    dark: 'bg-gray-800  text-white text-xl lg:text-2xl',
    dragon: 'bg-indigo-400  text-white text-xl lg:text-2xl',
    electric: 'bg-yellow-400  text-white text-xl lg:text-2xl',
    fairy: 'bg-pink-400  text-white text-xl lg:text-2xl',
    fighting: 'bg-red-400  text-white text-xl lg:text-2xl',
    fire: 'bg-red-400  text-white text-xl lg:text-2xl',
    flying: 'bg-blue-400  text-white text-xl lg:text-2xl',
    ghost: 'bg-purple-400  text-white text-xl lg:text-2xl ',
    grass: 'bg-green-400  text-white text-xl lg:text-2xl',
    ground: 'bg-yellow-900  text-white text-xl lg:text-2xl',
    ice: 'bg-blue-400  text-white text-xl lg:text-2xl',
    normal: 'bg-gray-400  text-white text-xl lg:text-2xl',
    poison: 'bg-purple-400  text-white text-xl lg:text-2xl',
    psychic: 'bg-pink-400  text-white text-xl lg:text-2xl',
    rock: 'bg-gray-600  text-white text-xl lg:text-2xl',
    steel: 'bg-gray-400  text-white text-xl lg:text-2xl',
    water: 'bg-blue-400  text-white text-xl lg:text-2xl',
    other: 'bg-gray-400  text-white text-xl lg:text-2xl',
}
